<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_adobe.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_apache_portal.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_asp.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_bash.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_bitcoin.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_cfg.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_cgi.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_cisco.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_cloudflare.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_db4web.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_dbm.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_domain_analyzer.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_exe.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_exploits.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_favicon.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_fts.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_hp.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_html.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_iis.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_ip_cameras.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_java.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_joomla.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_lua.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_ms_exchange.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_ms_word.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_mysqladmin.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_novell.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_ogate.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_oracle.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_panasonic_cameras.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_passwd.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_perl.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_php.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_sap.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_sftp.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_simatic_s7.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_sqlite.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_subversion.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_status.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_struts.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_txt.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_ubiquity.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_weblogic.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_wordpress.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_win_ini.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_xml.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_xsql.inc">Moved Permanently</a>.



<a href="/goodylabs/weird-paths/master/nginx/_weird_paths_yealink.inc">Moved Permanently</a>.



  # some custom rules

  rewrite  ^/some_custom_url                                    $redirect_ssl_host_url/ permanent;
